### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Ren-40424** [Ren-40424/furima-40424#20]
# URL
https://furima-40424.onrender.com/

# Basic認証
ID : `admin`
パスワード : `2222`

# ユーザーアカウント
## 出品者用
メールアドレス : `user1@mail`
パスワード : `password1`
## 購入者用
メールアドレス : `user2@mail`
パスワード : `password2`

**Comment by snkw-works** [comment]
@Ren-40424 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
#### 商品出品機能
- [x] **カテゴリーは、「---、メンズ、レディース、ベビー・キッズ、インテリア・住まい・小物、本・音楽・ゲーム、おもちゃ・ホビー・グッズ、家電・スマホ・カメラ、スポーツ・レジャー、ハンドメイド、その他」の11項目が表示されるよう修正しましょう（--- は初期値として設定すること）**
「本・音楽・ゲーム」の「ゲーム」が抜けている状態です。
<img width="867" alt="スクリーンショット 2024-04-28 15 28 37" src="https://github.com/Ren-40424/furima-40424/assets/54050089/3a1a9d42-66da-40ea-ac84-c5a384a387e4">

- [x] **入力された販売価格によって、販売手数料や販売利益が変わるよう修正しましょう(JavaScriptを使用して実装すること)**
出品機能・編集機能において、エラーハンドリングによって出品ページに戻ったあと、価格を再入力しても販売手数料や利益が変わらなくなります。どの状態でも変わるように修正をお願いします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Ren-40424** [comment]
対応頂きありがとうございます
指摘頂いた2点について修正しましたので、確認のほどよろしくお願いいたします！

**Comment by snkw-works** [comment]
@Ren-40424 さん、修正とご提出ありがとうございます‼︎
正常に動作することが確認できました！ **LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)

**Comment by Ren-40424** [comment]
ご確認いただきありがとうございます！
